name: 'Project-Env Github Action'
description: 'Sets up the runner environment with the Project-Env CLI'
branding:
  icon: 'box'
  color: 'gray-dark'
inputs:
  cli-version:
    description: 'Version of Project-Env CLI to use'
    required: true
  cli-debug:
    description: 'Whether to activate the debug mode of the Project-Env CLI'
    required: false
    default: 'false'
runs:
  using: 'node16'
  main: 'dist/index.js'
