name: 'Project-Env Github Action'
description: 'Sets up the runner environment with the Project-Env CLI'
inputs:
  cli-version:
    description: 'Version of Project-Env CLI to use'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'