tools_directory = ".tools"

[jdk]
version = "23.1.2"
distribution = "GraalVM CE 21"

[maven]
version = "3.6.3"

[gradle]
version = "6.7.1"

[nodejs]
version = "20.17.0"
post_extraction_commands = ["npm install -g yarn"]

[[generic]]
download_url = "https://repo1.maven.org/maven2/com/sun/xml/bind/jaxb-ri/3.0.0/jaxb-ri-3.0.0.zip"
environment_variables = { JAXB_HOME = "/" }
path_elements = ["bin"]

[[generic]]
download_urls = [
    { target_os = "macos", download_url = "https://fastdl.mongodb.org/tools/db/mongodb-database-tools-macos-x86_64-100.4.1.zip" },
    { target_os = "windows", download_url = "https://fastdl.mongodb.org/tools/db/mongodb-database-tools-windows-x86_64-100.4.1.zip" },
    { target_os = "linux", download_url = "https://fastdl.mongodb.org/tools/db/mongodb-database-tools-ubuntu2004-x86_64-100.4.1.tgz" }
]
path_elements = ["bin"]