name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-nodemodules-${{ hashFiles('package.json') }}
          restore-keys: ${{ runner.os }}-nodemodules
      - uses: Project-Env/project-env-github-action@v1.1.0
        with:
          cli-version: '3.4.0'
      - run: npm install
      - run: npm test